name: Microblog CICD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

  workflow_dispatch: # Can be run manually

permissions:
  contents: write # needed for 'write-deployment-log'

jobs:
  backend-test:
    uses: ./.github/workflows/backend-test.yml

  backend-notify:
    needs: backend-test
    if: always()
    uses: ./.github/workflows/notify-backend.yml
    with:
      job_start_time: ${{ needs.backend-test.outputs.job_start_time }}
      test_status: ${{ needs.backend-test.result }}
      build_status: ${{ needs.backend-docker-build.result }}
    secrets: inherit

  frontend-test:
    uses: ./.github/workflows/frontend-test.yml

  frontend-notify:
    needs: frontend-test
    if: always()
    uses: ./.github/workflows/notify-frontend.yml
    with:
      job_start_time: ${{ needs.frontend-test.outputs.job_start_time }}
      test_status: ${{ needs.frontend-test.result }}
      build_status: ${{ needs.frontend-docker-build.result }}
    secrets: inherit

  setup-remote-state:
    needs: [backend-test, frontend-test]
    uses: ./.github/workflows/setup-remote-state.yml
    with:
      storage-account-name: tfstateweek9infra
      container-name: tfstate
      location: westeurope
    secrets: inherit

  deploy-infrastructure:
    needs: setup-remote-state
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      storage-account-name: ${{ needs.setup-remote-state.outputs.storage_account_name }}
    secrets: inherit

  create-and-attach-disk:
    needs: deploy-infrastructure
    uses: ./.github/workflows/create-disk.yml
    secrets: inherit

  get-vm-ip:
    needs: deploy-infrastructure
    uses: ./.github/workflows/get-ip.yml
    secrets: inherit

  deploy-webapp:
    needs: get-vm-ip
    uses: ./.github/workflows/deploy-webapp.yml
    with:
      vm_ip: ${{ needs.get-vm-ip.outputs.vm_ip }}
    secrets: inherit

  healthcheck:
    needs: deploy-webapp
    uses: ./.github/workflows/healthcheck.yml
    secrets: inherit

  e2e-tests:
    needs: deploy-webapp
    uses: ./.github/workflows/e2e-tests.yml

  write-deployment-log:
    needs: healthcheck
    uses: ./.github/workflows/write-deployment-log.yml
    secrets: inherit